Revert "RealmeParts: Disable startup provider."
Fixes:
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider" on path: DexPathList[[zip file "/system/system_ext/priv-app/RealmeParts/RealmeParts.apk"],nativeLibraryDirectories=[/system/system_ext/priv-app/RealmeParts/lib/arm64, /system/lib64, /system/system_ext/lib64, /system/product/lib64, /system/lib64, /system/system_ext/lib64, /system/product/lib64]]

This reverts commit dcb8a178f59c1885cad309cd76153d80fa4729b3.